$storeMy = "Cert:\LocalMachine\My"
$storeRoot = "Cert:\LocalMachine\Root"


New-SelfSignedCertificate `
  -KeyLength 4096 `
  -DnsName "ggst-game.guiltygear.com", "localhost" `
  -CertStoreLocation $storeMy `
  -KeyLocation "c:\tools" `
  -KeyFriendlyName "generated by gg-struggle/tools/gencert.ps1" `
  -KeyDescription "gg-struggle-key" `
  -FriendlyName "gg-struggle" `

$certs = Get-ChildItem $storeMy `
 | where{$_.Subject -eq "CN=ggst-game.guiltygear.com"}

Foreach ($cert in $certs) {
  $certId = $cert.Thumbprint
  Move-Item -path $storeMy\$certId -Destination $storeRoot
}

#$certId = $cert.Thumbprint
#Move-Item -path $storeMy\$certId -Destination $storeRoot
#
#
#if (Test-Path -path Cert:\LocalMachine\Root\$certId)
#{
#  $cert = Get-Item -Path Cert:\LocalMachine\Root\$certId
#  $store = Get-Item -Path Cert:\LocalMachine\Root
#  $store.open("ReadWrite")
#  $store.Remove($cert)
#  $store.Close()
#  $untrusted = Get-Item -Path Cert:\LocalMachine\Disallowed
#  $untrusted.open("ReadWrite")
#  $untrusted.add($cert)
#  $untrusted.close()
#}
#Else
#{
#  write-host "$certId not found"
#}
