# NOTE: This must be run as admin!

# function defs
function Enable-Read {
  param (
    [string[]]$FilePath
  )

  # https://stackoverflow.com/questions/25779423/powershell-to-set-folder-permissions
  $Acl = Get-Acl $FilePath
  #$everyone = new SecurityIdentifier(WellKnownSidType.WorldSid, null)
  $Ar = New-Object System.Security.AccessControl.FileSystemAccessRule( "Everyone", "Read", "Allow")

  $Acl.SetAccessRule($Ar)
  Set-Acl $FilePath $Acl
  Write-Host "Enabled read permissions on $FilePath"
}

function Enable-Read {
  param (
    [string[]]$FilePath
  )

  # https://stackoverflow.com/questions/25779423/powershell-to-set-folder-permissions
  $Acl = Get-Acl $FilePath
  #$everyone = new SecurityIdentifier(WellKnownSidType.WorldSid, null)
  $Ar = New-Object System.Security.AccessControl.FileSystemAccessRule( "Everyone", "Read", "Allow")

  $Acl.SetAccessRule($Ar)
  Set-Acl $FilePath $Acl
  Write-Host "Enabled read permissions on $FilePath"
}

# entry point
if (($args.Count -lt 1) -or !(Test-Path $args[0])) {
  Write-Host "Usage: gencert.ps1 <outputDir>"
  Exit 5
}

$storeMy = "Cert:\LocalMachine\My"
$storeRoot = "Cert:\LocalMachine\Root"
$outputDir = Resolve-Path $args[0]
$hash = Get-Random
$tmpDir = "$Env:TEMP\$hash"
#$keyDst = "$outputDir\gg-struggle-key.pem"
#$certDst = "$outputDir\gg-struggle-cert.pem"
$certDstPfx = "$outputDir\gg-struggle-cert.pfx"

#Enable-Read $certDst
#Enable-Read $keyDst

$pkiCert = New-SelfSignedCertificate `
  -KeyLength 4096 `
  -DnsName "ggst-game.guiltygear.com", "localhost" `
  -CertStoreLocation $storeMy `
  -KeyFriendlyName "generated by gg-struggle/tools/gencert.ps1" `
  -KeyDescription "gg-struggle-key" `
  -FriendlyName "gg-struggle" `

$CertPassword = ConvertTo-SecureString -String "totsugeki" -Force -AsPlainText
Export-PfxCertificate -Cert $pkiCert -FilePath $certDstPfx -Password $CertPassword

Write-Host "Importing $storeMy\$certId to $storeRoot"
$certId = $pkiCert.Thumbprint
Move-Item -path $storeMy\$certId -Destination $storeRoot
