# This is a basic workflow to help you get started with Actions
name: Tag latest release
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  release:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
      with:
        # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
        # Optional
        description: Allows an auto-updater to pull the latest zip from URL

