- name: Run latest-tag
  uses: EndBug/latest-tag@latest
  with:
    # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
    # Optional
    description: Allows an auto-updater to pull the latest zip from URL

